services:

  shift-bob:
    image: shift-bob
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    command:
      - python
      - src/main.py
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 200M
