name: mypy
on: [ pull_request ]
jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: install poetry
        uses: snok/install-poetry@v1
      - name: install dependencies
        run: |
          poetry sync
      - name: run mypy
        run: |
          poetry run mypy src/ tests/
